import os
import subprocess

# Bestimmt das Verzeichnis automatisch anhand des Speicherorts dieses Skripts
directory = os.path.dirname(os.path.abspath(__file__))
image_dir = os.path.join(directory, "Bilder", "Fussball")

# Unterstützte Bildformate
valid_extensions = (".jpg", ".jpeg", ".png", ".gif", ".webp", ".bmp")

print(f"Scanne Ordner: {image_dir}...")

# Wir ermitteln die Bilddateien über zwei Wege (robust bei Google Drive Sync & Git):
image_files_set = set()

# 1. Über Git (falls vorhanden)
try:
    # Führe git ls-files für das Verzeichnis aus
    result = subprocess.run(
        ["git", "ls-files", "Bilder/Fussball"],
        capture_output=True,
        text=True,
        check=True
    )
    for line in result.stdout.splitlines():
        filename = os.path.basename(line)
        if filename.lower().endswith(valid_extensions):
            image_files_set.add(filename)
    print(f"  -> {len(image_files_set)} Bilder über Git-Index gefunden.")
except Exception:
    # Git ist nicht verfügbar oder kein Repo, wir überspringen das lautlos
    pass

# 2. Über das physische Verzeichnis (erweitert die Liste)
if os.path.exists(image_dir):
    physical_count = 0
    for filename in os.listdir(image_dir):
        if filename.lower().endswith(valid_extensions):
            if filename not in image_files_set:
                image_files_set.add(filename)
                physical_count += 1
    if physical_count > 0:
        print(f"  -> {physical_count} zusätzliche Bilder physisch auf der Festplatte gefunden.")
else:
    print(f"Warnung: Physisches Verzeichnis {image_dir} nicht gefunden.")

# Zur Liste konvertieren
image_files = list(image_files_set)

if not image_files:
    print("Keine Bilder gefunden!")
    exit(0)

# Sortierung: 1. Mannschaft, 2. Mannschaft, Mannschaftsbilder zuerst, danach alphabetisch
def sort_key(name):
    lower_name = name.lower()
    if "1_mannschaft" in lower_name:
        return (0, name)
    elif "2_mannschaft" in lower_name:
        return (1, name)
    elif "mannschaftsbild" in lower_name:
        return (2, name)
    else:
        return (3, name)

image_files.sort(key=sort_key)

# JS-Array-Einträge generieren
js_array_items = []
for filename in image_files:
    rel_path = f"Bilder/Fussball/{filename}"
    label = ""
    category = "Aktion"
    
    lower_name = filename.lower()
    if "1_mannschaft" in lower_name:
        label = "1. Herrenmannschaft"
        category = "Senioren"
    elif "2_mannschaft" in lower_name:
        label = "2. Herrenmannschaft"
        category = "Senioren"
    elif "frauen" in lower_name or "juniorinnen" in lower_name:
        label = "Frauenmannschaft"
        category = "Senioren"
    elif "alte_herren" in lower_name or "herren_03" in lower_name:
        label = "Alte Herren"
        category = "Senioren"
    elif "sportplatz" in lower_name:
        label = "Sportplatz"
        category = "Verein"
    elif "wolfgang" in lower_name:
        label = "Foto mit Wolfgang Frank"
        category = "Historie"
    elif "mannschaftsbild" in lower_name:
        label = "Mannschaftsbild"
        category = "Senioren"
        
    js_array_items.append(f'  {{ src: "{rel_path}", category: "{category}", title: "{label}" }}')

js_array_str = ",\n".join(js_array_items)
js_content = f"""// Auto-generated by generate_gallery_data.py
const galleryImages = [
{js_array_str}
];
"""

output_path = os.path.join(directory, "js", "gallery-data.js")

# Falls der Ordner js/ noch nicht existiert
os.makedirs(os.path.join(directory, "js"), exist_ok=True)

with open(output_path, "w", encoding="utf-8") as f:
    f.write(js_content)

print(f"Erfolgreich! gallery-data.js mit {len(image_files)} Bildern unter {output_path} aktualisiert.")
